/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.0 		*/
/*  Created On : 25-Feb-2017 10:24:27 PM 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `User` CASCADE
;

/* Create Tables */

CREATE TABLE `User`
(
	`firstName` VARCHAR(50) NULL,
	`lastName` VARCHAR(50) NULL,
	`userID` INT NOT NULL,
	`mailingAddress` VARCHAR(50) NULL,
	`billingAddress` VARCHAR(50) NULL,
	`phoneNumber` VARCHAR(50) NULL,
	`email` VARCHAR(50) NULL,
	`username` VARCHAR(50) NULL,
	`password` VARCHAR(50) NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`userID` ASC)
)

;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE `User` 
 ADD CONSTRAINT `UK_username` UNIQUE (`username` ASC)
;

ALTER TABLE `User` 
 ADD CONSTRAINT `UK_email` UNIQUE (`email` ASC)
;

SET FOREIGN_KEY_CHECKS=1 
;

/* Insert login info */

INSERT INTO 'User' ('username','password') VALUES ('myuser','mypassword');
